from certbot/dns-google
run apk add curl bash tree jq
run curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
run chmod +x ./kubectl && mv ./kubectl /usr/local/bin

copy entrypoint.sh entrypoint.sh
entrypoint bash entrypoint.sh google