AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Photomnemonic
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 30

Resources:
  ScreenshotFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: .
      Handler: index.handler
      Runtime: nodejs14.x
      Events:
        Screenshot:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /screenshot
            Method: get
            ContentHandling: CONVERT_TO_BINARY

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  ScreenshotApi:
    Description: "API Gateway endpoint URL for Prod stage for Screenshotn function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/prod/screenshot/"
  ScreenshotFunction:
    Description: "Screenshot Lambda Function ARN"
    Value: !GetAtt ScreenshotFunction.Arn
  ScreenshotFunctionIamRole:
    Description: "Implicit IAM Role created for Screenshot function"
    Value: !GetAtt ScreenshotFunctionRole.Arn
